#!/usr/bin/env bash

# Stream server demo: Streams file passed as parameter to client
#
# Usage:
# 
# In one terminal run server:
# ncat -e "./stream-server-demo <filepath>" -lk 8080
# 
# In another terminal run client:
# curl localhost:8080
#
# Now in another terminal run server-feed:
# cat > <filepath>
# 
# Whatever you type in the 3rd terminal (server-feed) will be shown in the 2nd (client).
#
# Close the connection with client:
# kill <number shown in 1st terminal>

. ./sertain.bash
status 200 OK
header Content-Type text/plain
ul_stream < <(tail -F "${1}" 2>/dev/null)
